version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  deploy:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/circleci-docs-deploy
    steps:
      - add_ssh_keys:
        fingerprints:
          - "97:58:f6:1f:13:70:34:95:6b:04:6b:2e:84:e4:43:ff"
      - checkout      
      - run: sudo pip install mkdocs
      - run: mkdocs build
      - run:
          command: pwd && ls -la site
      - run:
          command: ~/circleci-docs-deploy/.circleci/scripts/deploy-ghpages.sh site
      
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - deploy
#      - build
#      - test:
#          requires:
#            - build
#      - deploy:
#          requires:
#            - test
#          filters:
#            branches:
#              only: circleci-20-test
           
